/*
* generated by Xtext
*/

package de.sebastianbenz.task.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;


@Singleton
public class TaskGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class TaskModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TaskModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTaskModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cContentsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cContentsContentParserRuleCall_1_0 = (RuleCall)cContentsAssignment_1.eContents().get(0);
		private final RuleCall cWsParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//TaskModel:
		//	{TaskModel} contents+=Content* Ws*;
		public ParserRule getRule() { return rule; }

		//{TaskModel} contents+=Content* Ws*
		public Group getGroup() { return cGroup; }

		//{TaskModel}
		public Action getTaskModelAction_0() { return cTaskModelAction_0; }

		//contents+=Content*
		public Assignment getContentsAssignment_1() { return cContentsAssignment_1; }

		//Content
		public RuleCall getContentsContentParserRuleCall_1_0() { return cContentsContentParserRuleCall_1_0; }

		//Ws*
		public RuleCall getWsParserRuleCall_2() { return cWsParserRuleCall_2; }
	}

	public class ContentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Content");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cProjectParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTaskParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cNoteParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cEmptyLineParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cCodeParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		/// *
		//Project
		//Ws TASK
		//Ws PROJECT
		//Ws Ws TASK
		//Ws Ws PROJECT 
		// * / Content:
		//	Project | Task | Note | EmptyLine | Code;
		public ParserRule getRule() { return rule; }

		//Project | Task | Note | EmptyLine | Code
		public Alternatives getAlternatives() { return cAlternatives; }

		//Project
		public RuleCall getProjectParserRuleCall_0() { return cProjectParserRuleCall_0; }

		//Task
		public RuleCall getTaskParserRuleCall_1() { return cTaskParserRuleCall_1; }

		//Note
		public RuleCall getNoteParserRuleCall_2() { return cNoteParserRuleCall_2; }

		//EmptyLine
		public RuleCall getEmptyLineParserRuleCall_3() { return cEmptyLineParserRuleCall_3; }

		//Code
		public RuleCall getCodeParserRuleCall_4() { return cCodeParserRuleCall_4; }
	}

	public class TaskElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Task");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIntendAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cIntendIntendationParserRuleCall_0_0 = (RuleCall)cIntendAssignment_0.eContents().get(0);
		private final Assignment cTextAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTextTASK_TEXTTerminalRuleCall_1_0 = (RuleCall)cTextAssignment_1.eContents().get(0);
		
		//Task:
		//	intend=Intendation text=TASK_TEXT;
		public ParserRule getRule() { return rule; }

		//intend=Intendation text=TASK_TEXT
		public Group getGroup() { return cGroup; }

		//intend=Intendation
		public Assignment getIntendAssignment_0() { return cIntendAssignment_0; }

		//Intendation
		public RuleCall getIntendIntendationParserRuleCall_0_0() { return cIntendIntendationParserRuleCall_0_0; }

		//text=TASK_TEXT
		public Assignment getTextAssignment_1() { return cTextAssignment_1; }

		//TASK_TEXT
		public RuleCall getTextTASK_TEXTTerminalRuleCall_1_0() { return cTextTASK_TEXTTerminalRuleCall_1_0; }
	}

	public class NoteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Note");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIntendAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cIntendIntendationParserRuleCall_0_0 = (RuleCall)cIntendAssignment_0.eContents().get(0);
		private final Assignment cTextAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTextTEXTTerminalRuleCall_1_0 = (RuleCall)cTextAssignment_1.eContents().get(0);
		
		//Note:
		//	intend=Intendation text=TEXT;
		public ParserRule getRule() { return rule; }

		//intend=Intendation text=TEXT
		public Group getGroup() { return cGroup; }

		//intend=Intendation
		public Assignment getIntendAssignment_0() { return cIntendAssignment_0; }

		//Intendation
		public RuleCall getIntendIntendationParserRuleCall_0_0() { return cIntendIntendationParserRuleCall_0_0; }

		//text=TEXT
		public Assignment getTextAssignment_1() { return cTextAssignment_1; }

		//TEXT
		public RuleCall getTextTEXTTerminalRuleCall_1_0() { return cTextTEXTTerminalRuleCall_1_0; }
	}

	public class ProjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Project");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIntendAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cIntendIntendationParserRuleCall_0_0 = (RuleCall)cIntendAssignment_0.eContents().get(0);
		private final Assignment cTextAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTextPROJECT_TerminalRuleCall_1_0 = (RuleCall)cTextAssignment_1.eContents().get(0);
		
		//Project:
		//	intend=Intendation text=PROJECT_;
		public ParserRule getRule() { return rule; }

		//intend=Intendation text=PROJECT_
		public Group getGroup() { return cGroup; }

		//intend=Intendation
		public Assignment getIntendAssignment_0() { return cIntendAssignment_0; }

		//Intendation
		public RuleCall getIntendIntendationParserRuleCall_0_0() { return cIntendIntendationParserRuleCall_0_0; }

		//text=PROJECT_
		public Assignment getTextAssignment_1() { return cTextAssignment_1; }

		//PROJECT_
		public RuleCall getTextPROJECT_TerminalRuleCall_1_0() { return cTextPROJECT_TerminalRuleCall_1_0; }
	}

	public class CodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Code");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIntendAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cIntendIntendationParserRuleCall_0_0 = (RuleCall)cIntendAssignment_0.eContents().get(0);
		private final Assignment cTextAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTextCODE_TerminalRuleCall_1_0 = (RuleCall)cTextAssignment_1.eContents().get(0);
		
		//Code:
		//	intend=Intendation text=CODE_;
		public ParserRule getRule() { return rule; }

		//intend=Intendation text=CODE_
		public Group getGroup() { return cGroup; }

		//intend=Intendation
		public Assignment getIntendAssignment_0() { return cIntendAssignment_0; }

		//Intendation
		public RuleCall getIntendIntendationParserRuleCall_0_0() { return cIntendIntendationParserRuleCall_0_0; }

		//text=CODE_
		public Assignment getTextAssignment_1() { return cTextAssignment_1; }

		//CODE_
		public RuleCall getTextCODE_TerminalRuleCall_1_0() { return cTextCODE_TerminalRuleCall_1_0; }
	}

	public class IntendationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Intendation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final RuleCall cSPACETerminalRuleCall_0_0_0 = (RuleCall)cGroup_0_0.eContents().get(0);
		private final RuleCall cSPACETerminalRuleCall_0_0_1 = (RuleCall)cGroup_0_0.eContents().get(1);
		private final RuleCall cTABTerminalRuleCall_0_1 = (RuleCall)cAlternatives_0.eContents().get(1);
		private final RuleCall cSPACETerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Intendation:
		//	(SPACE SPACE | TAB)* SPACE?;
		public ParserRule getRule() { return rule; }

		//(SPACE SPACE | TAB)* SPACE?
		public Group getGroup() { return cGroup; }

		//(SPACE SPACE | TAB)*
		public Alternatives getAlternatives_0() { return cAlternatives_0; }

		//SPACE SPACE
		public Group getGroup_0_0() { return cGroup_0_0; }

		//SPACE
		public RuleCall getSPACETerminalRuleCall_0_0_0() { return cSPACETerminalRuleCall_0_0_0; }

		//SPACE
		public RuleCall getSPACETerminalRuleCall_0_0_1() { return cSPACETerminalRuleCall_0_0_1; }

		//TAB
		public RuleCall getTABTerminalRuleCall_0_1() { return cTABTerminalRuleCall_0_1; }

		//SPACE?
		public RuleCall getSPACETerminalRuleCall_1() { return cSPACETerminalRuleCall_1; }
	}

	public class EmptyLineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EmptyLine");
		private final Assignment cTextAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cTextSpacesParserRuleCall_0 = (RuleCall)cTextAssignment.eContents().get(0);
		
		//EmptyLine:
		//	text=Spaces;
		public ParserRule getRule() { return rule; }

		//text=Spaces
		public Assignment getTextAssignment() { return cTextAssignment; }

		//Spaces
		public RuleCall getTextSpacesParserRuleCall_0() { return cTextSpacesParserRuleCall_0; }
	}

	public class SpacesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Spaces");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cWsParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final RuleCall cNLTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Spaces:
		//	Ws* NL;
		public ParserRule getRule() { return rule; }

		//Ws* NL
		public Group getGroup() { return cGroup; }

		//Ws*
		public RuleCall getWsParserRuleCall_0() { return cWsParserRuleCall_0; }

		//NL
		public RuleCall getNLTerminalRuleCall_1() { return cNLTerminalRuleCall_1; }
	}

	public class WsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Ws");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSPACETerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTABTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Ws:
		//	SPACE | TAB;
		public ParserRule getRule() { return rule; }

		//SPACE | TAB
		public Alternatives getAlternatives() { return cAlternatives; }

		//SPACE
		public RuleCall getSPACETerminalRuleCall_0() { return cSPACETerminalRuleCall_0; }

		//TAB
		public RuleCall getTABTerminalRuleCall_1() { return cTABTerminalRuleCall_1; }
	}
	
	
	private TaskModelElements pTaskModel;
	private ContentElements pContent;
	private TaskElements pTask;
	private NoteElements pNote;
	private ProjectElements pProject;
	private CodeElements pCode;
	private IntendationElements pIntendation;
	private EmptyLineElements pEmptyLine;
	private SpacesElements pSpaces;
	private WsElements pWs;
	private TerminalRule tSPACE;
	private TerminalRule tTAB;
	private TerminalRule tNL;
	private TerminalRule tCODE_;
	private TerminalRule tTASK_TEXT;
	private TerminalRule tTEXT;
	private TerminalRule tPROJECT_;
	private TerminalRule tCOLON;
	private TerminalRule tHYPHEN;
	
	private final Grammar grammar;

	@Inject
	public TaskGrammarAccess(GrammarProvider grammarProvider) {
		this.grammar = internalFindGrammar(grammarProvider);
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.sebastianbenz.task.Task".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	
	//TaskModel:
	//	{TaskModel} contents+=Content* Ws*;
	public TaskModelElements getTaskModelAccess() {
		return (pTaskModel != null) ? pTaskModel : (pTaskModel = new TaskModelElements());
	}
	
	public ParserRule getTaskModelRule() {
		return getTaskModelAccess().getRule();
	}

	/// *
	//Project
	//Ws TASK
	//Ws PROJECT
	//Ws Ws TASK
	//Ws Ws PROJECT 
	// * / Content:
	//	Project | Task | Note | EmptyLine | Code;
	public ContentElements getContentAccess() {
		return (pContent != null) ? pContent : (pContent = new ContentElements());
	}
	
	public ParserRule getContentRule() {
		return getContentAccess().getRule();
	}

	//Task:
	//	intend=Intendation text=TASK_TEXT;
	public TaskElements getTaskAccess() {
		return (pTask != null) ? pTask : (pTask = new TaskElements());
	}
	
	public ParserRule getTaskRule() {
		return getTaskAccess().getRule();
	}

	//Note:
	//	intend=Intendation text=TEXT;
	public NoteElements getNoteAccess() {
		return (pNote != null) ? pNote : (pNote = new NoteElements());
	}
	
	public ParserRule getNoteRule() {
		return getNoteAccess().getRule();
	}

	//Project:
	//	intend=Intendation text=PROJECT_;
	public ProjectElements getProjectAccess() {
		return (pProject != null) ? pProject : (pProject = new ProjectElements());
	}
	
	public ParserRule getProjectRule() {
		return getProjectAccess().getRule();
	}

	//Code:
	//	intend=Intendation text=CODE_;
	public CodeElements getCodeAccess() {
		return (pCode != null) ? pCode : (pCode = new CodeElements());
	}
	
	public ParserRule getCodeRule() {
		return getCodeAccess().getRule();
	}

	//Intendation:
	//	(SPACE SPACE | TAB)* SPACE?;
	public IntendationElements getIntendationAccess() {
		return (pIntendation != null) ? pIntendation : (pIntendation = new IntendationElements());
	}
	
	public ParserRule getIntendationRule() {
		return getIntendationAccess().getRule();
	}

	//EmptyLine:
	//	text=Spaces;
	public EmptyLineElements getEmptyLineAccess() {
		return (pEmptyLine != null) ? pEmptyLine : (pEmptyLine = new EmptyLineElements());
	}
	
	public ParserRule getEmptyLineRule() {
		return getEmptyLineAccess().getRule();
	}

	//Spaces:
	//	Ws* NL;
	public SpacesElements getSpacesAccess() {
		return (pSpaces != null) ? pSpaces : (pSpaces = new SpacesElements());
	}
	
	public ParserRule getSpacesRule() {
		return getSpacesAccess().getRule();
	}

	//Ws:
	//	SPACE | TAB;
	public WsElements getWsAccess() {
		return (pWs != null) ? pWs : (pWs = new WsElements());
	}
	
	public ParserRule getWsRule() {
		return getWsAccess().getRule();
	}

	//terminal SPACE:
	//	" ";
	public TerminalRule getSPACERule() {
		return (tSPACE != null) ? tSPACE : (tSPACE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SPACE"));
	} 

	//terminal TAB:
	//	"\t";
	public TerminalRule getTABRule() {
		return (tTAB != null) ? tTAB : (tTAB = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "TAB"));
	} 

	//terminal NL:
	//	"\r"? "\n";
	public TerminalRule getNLRule() {
		return (tNL != null) ? tNL : (tNL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NL"));
	} 

	//terminal CODE_:
	//	"\'\'\'"->"\'\'\'" NL?;
	public TerminalRule getCODE_Rule() {
		return (tCODE_ != null) ? tCODE_ : (tCODE_ = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "CODE_"));
	} 

	//terminal TASK_TEXT:
	//	HYPHEN !("\n" | "\r")* NL?;
	public TerminalRule getTASK_TEXTRule() {
		return (tTASK_TEXT != null) ? tTASK_TEXT : (tTASK_TEXT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "TASK_TEXT"));
	} 

	//terminal TEXT:
	//	(!(HYPHEN | COLON | "\n" | "\r" | SPACE | TAB) | !(HYPHEN | "\n" | "\r" | SPACE | TAB) !("\n" | "\r")* !(COLON | "\n"
	//	| "\r")) NL?;
	public TerminalRule getTEXTRule() {
		return (tTEXT != null) ? tTEXT : (tTEXT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "TEXT"));
	} 

	//terminal PROJECT_:
	//	!("\n" | "\r" | HYPHEN | SPACE | TAB) !("\n" | "\r")* COLON NL?;
	public TerminalRule getPROJECT_Rule() {
		return (tPROJECT_ != null) ? tPROJECT_ : (tPROJECT_ = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "PROJECT_"));
	} 

	//terminal fragment COLON:
	//	":";
	public TerminalRule getCOLONRule() {
		return (tCOLON != null) ? tCOLON : (tCOLON = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "COLON"));
	} 

	//terminal fragment HYPHEN:
	//	"-";
	public TerminalRule getHYPHENRule() {
		return (tHYPHEN != null) ? tHYPHEN : (tHYPHEN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "HYPHEN"));
	} 
}
