/*
 * generated by Xtext
 */
package de.sebastianbenz.task.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.XtextEditor;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

import com.google.inject.Binder;

import de.sebastianbenz.task.ui.highlighting.AntlrTokenToAttributeMapper;
import de.sebastianbenz.task.ui.highlighting.Configuration;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TaskPaperUiModule extends de.sebastianbenz.task.ui.AbstractTaskPaperUiModule {
	public TaskPaperUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.bind(XtextEditor.class).to(TaskEditor.class);
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return Configuration.class;
	}
	
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return AntlrTokenToAttributeMapper.class;
	}
	
}
