
/*
 * generated by Xtext
 */
package de.sebastianbenz.task.generator;

import static com.google.common.collect.Iterables.filter;

import java.util.List;

import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.xtext.generator.JavaIoFileSystemAccess;
import org.eclipse.xtext.util.CancelIndicator;
import org.eclipse.xtext.validation.CheckMode;
import org.eclipse.xtext.validation.IResourceValidator;
import org.eclipse.xtext.validation.Issue;

import com.google.inject.Inject;
import com.google.inject.Injector;
import com.google.inject.Provider;

import de.sebastianbenz.task.TaskModel;

public class Main {
	
	public static void main(String[] args) {
		if (args.length==0) {
			System.err.println("Aborting: no path to EMF resource provided!");
			return;
		}
		Injector injector = new de.sebastianbenz.task.TaskStandaloneSetup().createInjectorAndDoEMFRegistration();
		Main main = injector.getInstance(Main.class);
		main.runGenerator(args[0]);
	}
	
	@Inject 
	private Provider<ResourceSet> resourceSetProvider;
	
	@Inject
	private IResourceValidator validator;
	
	@Inject 
	private JavaIoFileSystemAccess fileAccess;
	
	@Inject
	private ConfluenceGenerator confluenceGenerator;
	
	@Inject
	private MarkdownGenerator markDownGenerator;
	
	@Inject
	private HtmlGenerator htmlGenerator;

	protected void runGenerator(String string) {
		// load the resource
		ResourceSet set = resourceSetProvider.get();
		Resource resource = set.getResource(URI.createURI(string), true);
		
		// validate the resource
		List<Issue> list = validator.validate(resource, CheckMode.ALL, CancelIndicator.NullImpl);
		if (!list.isEmpty()) {
			for (Issue issue : list) {
				System.err.println(issue);
			}
			return;
		}
		
		// configure and start the generator
		fileAccess.setOutputPath("src-gen/");
		for (TaskModel taskModel: filter(resource.getContents(), TaskModel.class)) {
			fileAccess.generateFile(string.replace(".todo", ".confluence"), confluenceGenerator.generate(taskModel));
			fileAccess.generateFile(string.replace(".todo", ".markdown"), markDownGenerator.generate(taskModel));
			fileAccess.generateFile(string.replace(".todo", ".html"), htmlGenerator.generate(taskModel));
		} 
		
		System.out.println("Code generation finished.");
	}
}
