/*
 * generated by Xtext
 */
package de.sebastianbenz.task.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.IGenerator
import org.eclipse.xtext.generator.IFileSystemAccess

class TaskPaperGenerator implements IGenerator {
	
	void doGenerate(Resource resource, IFileSystemAccess fsa) {
		//TODO implment me
	}
}
