/*
* generated by Xtext
*/
package de.sebastianbenz.task.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class TaskPaperOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
