/*
 * generated by Xtext
 */
package de.sebastianbenz.task.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.sebastianbenz.task.ui.internal.TaskActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class QueryExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TaskActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TaskActivator.getInstance().getInjector(TaskActivator.DE_SEBASTIANBENZ_TASK_QUERY);
	}
	
}
