/*
* generated by Xtext
*/
package de.sebastianbenz.task.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

import de.sebastianbenz.task.services.TaskPaperGrammarAccess;

public class TaskPaperParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TaskPaperGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens();
	}
	
	@Override
	protected de.sebastianbenz.task.parser.antlr.internal.InternalTaskPaperParser createParser(XtextTokenStream stream) {
		return new de.sebastianbenz.task.parser.antlr.internal.InternalTaskPaperParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Todo";
	}
	
	public TaskPaperGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TaskPaperGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
