/*
* generated by Xtext
*/
package de.sebastianbenz.task.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TaskAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/sebastianbenz/task/parser/antlr/internal/InternalTask.tokens");
	}
}
