/*
* generated by Xtext
*/
package de.sebastianbenz.task.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

import de.sebastianbenz.task.services.TaskGrammarAccess;

public class TaskParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TaskGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens();
	}
	
	@Override
	protected de.sebastianbenz.task.parser.antlr.internal.InternalTaskParser createParser(XtextTokenStream stream) {
		return new de.sebastianbenz.task.parser.antlr.internal.InternalTaskParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TaskModel";
	}
	
	public TaskGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TaskGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
