/*******************************************************************************
 * Copyright (c) 2011 Sebastian Benz.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Sebastian Benz - initial API and implementation
 *******************************************************************************/
/*
 * generated by Xtext
 */
package de.sebastianbenz.task;

import org.eclipse.xtext.resource.ILocationInFileProvider;

import de.sebastianbenz.task.resource.LocationInFileProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TaskPaperRuntimeModule extends de.sebastianbenz.task.AbstractTaskPaperRuntimeModule {

	public Class<? extends ILocationInFileProvider> bindILocationInFileProvider() {
		return LocationInFileProvider.class;
	}
	
}
