/*
* generated by Xtext
*/
package de.sebastianbenz.task.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import de.sebastianbenz.task.services.TaskPaperGrammarAccess;

public class TaskPaperParser extends AbstractContentAssistParser {
	
	@Inject
	private TaskPaperGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected de.sebastianbenz.task.ui.contentassist.antlr.internal.InternalTaskPaperParser createParser() {
		de.sebastianbenz.task.ui.contentassist.antlr.internal.InternalTaskPaperParser result = new de.sebastianbenz.task.ui.contentassist.antlr.internal.InternalTaskPaperParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getContentAccess().getAlternatives(), "rule__Content__Alternatives");
					put(grammarAccess.getTaskAccess().getAlternatives(), "rule__Task__Alternatives");
					put(grammarAccess.getProjectAccess().getTextAlternatives_2_0(), "rule__Project__TextAlternatives_2_0");
					put(grammarAccess.getTodoAccess().getGroup(), "rule__Todo__Group__0");
					put(grammarAccess.getOpenTaskAccess().getGroup(), "rule__OpenTask__Group__0");
					put(grammarAccess.getClosedTaskAccess().getGroup(), "rule__ClosedTask__Group__0");
					put(grammarAccess.getProjectAccess().getGroup(), "rule__Project__Group__0");
					put(grammarAccess.getProjectAccess().getGroup_1(), "rule__Project__Group_1__0");
					put(grammarAccess.getTodoAccess().getContentsAssignment_1(), "rule__Todo__ContentsAssignment_1");
					put(grammarAccess.getOpenTaskAccess().getTextAssignment_1(), "rule__OpenTask__TextAssignment_1");
					put(grammarAccess.getClosedTaskAccess().getTextAssignment_1(), "rule__ClosedTask__TextAssignment_1");
					put(grammarAccess.getNoteAccess().getTextAssignment(), "rule__Note__TextAssignment");
					put(grammarAccess.getProjectAccess().getIntendAssignment_1_0(), "rule__Project__IntendAssignment_1_0");
					put(grammarAccess.getProjectAccess().getTextAssignment_2(), "rule__Project__TextAssignment_2");
					put(grammarAccess.getSpacesAccess().getTextAssignment(), "rule__Spaces__TextAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			de.sebastianbenz.task.ui.contentassist.antlr.internal.InternalTaskPaperParser typedParser = (de.sebastianbenz.task.ui.contentassist.antlr.internal.InternalTaskPaperParser) parser;
			typedParser.entryRuleTodo();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] {  };
	}
	
	public TaskPaperGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TaskPaperGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
