/*******************************************************************************
 * Copyright (c) 2011 Sebastian Benz.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Sebastian Benz - initial API and implementation
 *******************************************************************************/
/*
* generated by Xtext
*/
package de.sebastianbenz.task.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

import com.google.inject.Inject;

import de.sebastianbenz.task.Tag;
import de.sebastianbenz.task.tagging.TagProvider;
import de.sebastianbenz.task.tagging.Tags;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TaskProposalProvider extends AbstractTaskProposalProvider {

	@Inject
	private TagProvider tagProvider;
	
	@Override
	public void completeTask_Text(EObject model, Assignment assignment,
			ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		Tag done = Tags.from("done");
		createProposal(model, context, acceptor, done);
		for (Tag tag : tagProvider.in(model.eResource())) {
			createProposal(model, context, acceptor, tag);
		}
	}
	

	protected void createProposal(EObject model, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor, Tag tag) {
		String prefix = context.getPrefix();
		if(prefix.trim().startsWith("-") && !prefix.contains("@" + tag.getName())){
			acceptor.accept(
					createCompletionProposal(
							prefix+ tag, 
							getStyledDisplayString(model, tag.getName(), tag.getName()), 
							getLabelProvider().getImage(tag), 
							0, 
							"", 
							context));
		}
	}
	
}
